apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev

---

apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: ghcr-credentials
  namespace: dev
data:
  .dockerconfigjson: xxx

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: de-tommzn-kafka-march-test
  namespace: dev
  labels:
    app: de-tommzn-kafka-march-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: de-tommzn-kafka-march-test
  template:
    metadata:
      labels:
        app: de-tommzn-kafka-march-test
    spec:
      containers:
        - name: de-tommzn-kafka-march-test
          image: ghcr.io/tommzn/kafka-march-test:latest
          imagePullPolicy: Always  
      imagePullSecrets:
        - name: ghcr-credentials

