name: Multi Arch Image Build

on:
  create:
    tags:
      - 'v*'

jobs:
  go-image-build:
    uses:  tommzn/github-ci/.github/workflows/go.image.multiarch.build.yml@v1.0.58
    secrets:
      cr-pat: ${{ secrets.CR_PAT }}
